### ISSUE TITLE
Creating simple colored radio

### ISSUE THREAD

**Issue by richbl** [lokesh-coder/pretty-checkbox#1]
Very good library. 

I have a simple question: how to create a simple solid-colored radio, such as this:

![image](https://cloud.githubusercontent.com/assets/10182110/16966285/b0c462da-4db8-11e6-98b0-51d727bfbacc.png)

Attempting to use FA won't work because the icon is inverted (color), so I'm not sure how best to proceed using this library.

Thanks

**Comment by lokesh-coder** [comment]
hey @richbl , thanks for raising this question. 

I have updated the Repo and Documentation for default radio checked style.
https://lokesh-coder.github.io/pretty-checkbox/#radio

Here's how the radio button markup looks,
```html
<div class="pretty inline circle">
  <input type="radio" name="basic_radio"> 
  <label><i class="default"></i> choose</label>
</div>
```
Have to add `default` class to `i` tag, if you not wanted to use any icons for that.

Thanks!

**Comment by richbl** [comment]
Looks great.

Please let me know when you've pushed the update to npm, and I'll give it a go.

Thanks

**Comment by lokesh-coder** [comment]
Its updated. Go ahead and give it a try. :)

**Comment by richbl** [comment]
Got the update. Looks great.

Thanks
