### ISSUE TITLE
Does this library has dependecies on materialdesignicons css file

### ISSUE THREAD

**Issue by rajmondburgaj** [lokesh-coder/pretty-checkbox#15]
I included the cdn link to my project where I am using bootstrap 3 and fontawesome. But it did not work as expected. While digging to your page html code I could see this library does not function properly if there is not included this link `<link rel="stylesheet" href="https://cdn.materialdesignicons.com/1.8.36/css/materialdesignicons.min.css"/>`. Is this mandatory to include this link to my project or there is something else to do in order to use only fontawesome icons ?

**Comment by lokesh-coder** [comment]
Hi @rajmondburgaj ,

If you are using `fontawesome`, you don't need to use `material design icons`. I am quite unsure what could be the problem. If you can able to post the snippet you are using, I can help you.

In general this should work,
```html
<div class="pretty success">
  <input type="checkbox"> 
  <label><i class="fa fa-check"></i> fa-check</label>
</div>
```

**Comment by lokesh-coder** [comment]
Closing now. Feel free to open if you still face the issue.
Thanks!
