### ISSUE TITLE
Google Material Design Icons not compatible with IE 11

### ISSUE THREAD

**Issue by DavidMaza** [lokesh-coder/pretty-checkbox#16]
The Google Material Design Icons in pretty-checkbox aren't compatible with IE 11 and display as large square boxes.

https://lokesh-coder.github.io/pretty-checkbox/

![ie](https://user-images.githubusercontent.com/2233700/30093834-9e27b338-92fa-11e7-9421-f3fbc67e4a4f.gif)

**Comment by lokesh-coder** [comment]
Hi @DavidMaza ,

Issue has been fixed in new [version 3](https://github.com/lokesh-coder/pretty-checkbox/blob/master/README.md). 
Here's the updated [documentation](https://lokesh-coder.github.io/pretty-checkbox/#fonticon-lib) 

Feel free to open if you face the same issue.
Thanks!
