### ISSUE TITLE
Feature for `lock`

### ISSUE THREAD

**Issue by Viky-zhang** [lokesh-coder/pretty-checkbox#17]
Sometime I want to lock the checkbox/radio, and don't to change the color. 

`disabled` will change color. 

Is there any plan to add feature for `lock` ?

**Comment by lokesh-coder** [comment]
Hi @Viky-zhang ,

Added [Lock](https://lokesh-coder.github.io/pretty-checkbox/#lock) feature.

But the library is updated to version 3 with no backward compatibility.

Thanks!
