### ISSUE TITLE
Checkbox not showing?

### ISSUE THREAD

**Issue by maxiedaniels** [lokesh-coder/pretty-checkbox#29]
I've checked in both Safari and Chrome.. checkboxes aren't showing. Not sure why... I've imported at the top of my index.html page (`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css"/>`).

I'm using vue but I don't see why that would affect it...

```
<div class="pretty p-switch">
<input type="checkbox" id="checkbox" v-model="item.enabled" v-on:change="change_active(item)">
</div>
<div class="state">
<label>Check</label>
</div>
```

**Comment by lokesh-coder** [comment]
Hi @maxiedaniels ,

The problem is with the markup. Please try this,

```html
<div class="pretty p-switch">
  <input type="checkbox" id="checkbox" v-model="item.enabled" v-on:change="change_active(item)">
  <div class="state">
    <label>Check</label>
  </div>
</div>
```

> the `state` class element should be inside `pretty` tag

Let me know, if that doesn't solved the issue.

**Comment by maxiedaniels** [comment]
Ah, that was it. My bad! Thank you!
