### ISSUE TITLE
Checkbox not aligned

### ISSUE THREAD

**Issue by LastxTemplar** [lokesh-coder/pretty-checkbox#37]
The checkbox doesn't seem to align correctly no matter where I put it in the document.
I managed to make it align by writing some messy css around it but I really don't like that solution.

Here is an image for reference: [https://imgur.com/yuVtiMX](https://imgur.com/yuVtiMX)

**Comment by lokesh-coder** [comment]
Hi @LastxTemplar ,

I got the issue. I am already in middle of newer version. So, the new update will fix that.

**Comment by LastxTemplar** [comment]
awesome, thanks for the reply!
