### ISSUE TITLE
How to change the default colors?

### ISSUE THREAD

**Issue by preethammadapura** [lokesh-coder/pretty-checkbox#38]
Under customize, you have mentioned we can change the default colors. But where and how? I am using your library as part of a Vue.js project. I have imported your scss stylesheet. But overwriting the scss style in the local code is not changing the color. Please help.

**Comment by lokesh-coder** [comment]
Hi @preethammadapura ,

In general this should work,
```scss
@import '~pretty-checkbox/src/scss/variables';

$pretty--colors:(
  primary:#3f51b5,
  info:#00bcd4,
  success:#4caf50,
  warning:$pretty--color-warning, // default
  danger:$pretty--color-danger //default
);

@import '~pretty-checkbox/src/pretty-checkbox.scss';

```

Also please check this for adding more colors,
**Demo:** https://pretty-checkbox-custom-colors-demo.stackblitz.io/
**Code:** https://stackblitz.com/edit/pretty-checkbox-custom-colors-demo?embed=1&file=styles.scss&view=editor

Let me know if that helps!

**Comment by preethammadapura** [comment]
That worked like charm. I was just doing the changes in the wrong place. Thanks for your fast response. This was super helpful!

**Comment by goranGG** [comment]
@lokesh-coder hey - can you update website with this example, it would be super useful because I tried to paste thinks from there in same area and it didn't work
