### ISSUE TITLE
They don't print

### ISSUE THREAD

**Issue by swrobel** [lokesh-coder/pretty-checkbox#4]
Any idea why this is? I get a � instead of the checkbox on Safari, Firefox and Chrome on my Mac.

**Comment by benmcmaster** [comment]
I am seeing the same issue. If you print the demo page you will see the issue:
https://lokesh-coder.github.io/pretty-checkbox/

In the library that inspired this one everything prints fine:
https://github.com/flatlogic/awesome-bootstrap-checkbox

@lokesh-coder Any ideas of how we can make this print correctly?

**Comment by lokesh-coder** [comment]
Thanks @swrobel and @benmcmaster  for pointing out this issue. I never thought of printing :)

I have updated the repo ( v2.0.4 ). Hope this will fix the issue in all browsers.

**Comment by swrobel** [comment]
I'm not sure if the demo site has been updated or not, but I still see the issue there. It's worth noting that this Bootstrap rule seems to be causing the invisible character to display on print media: https://github.com/twbs/bootstrap/blob/v3.3.6/less/print.less#L13

**Comment by lokesh-coder** [comment]
Yes, the demo site is not yet updated. Actually the junk character is created to calculate the approximate size of the icon, to draw the checkbox border. 

https://github.com/lokesh-coder/pretty-checkbox/blob/master/src/scss/decorators/_core.scss#L37

Just after you pointed out the issue, I realized the junk character should be transparent in print media as well. 

Thanks for checking.. :)

**Comment by benmcmaster** [comment]
Awesome. Thanks! That change plus removing bootstrap printed styles solved the issue. Although I noticed that you added some !important styles around that broke some of my overrides. All good. I just had to add some !important styles on my overrides.
