### ISSUE TITLE
Doesn't work with the official Material Icons from Google

### ISSUE THREAD

**Issue by michaelhertig** [lokesh-coder/pretty-checkbox#5]
The library seems not to work with the official Google Material Icons from here: [https://material.io/icons/](https://material.io/icons/). 

I imported pretty.css with the following link:
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pretty-checkbox/2.2.0/pretty.min.css"/>
```

My markup is as follow:
```
<div class="pretty">
        <label for="isSSL"><i class="material-icons">done</i> labeltext</label>
        <input type="checkbox" name="isSSL" />
</div>
```

**Comment by lokesh-coder** [comment]
Hi @michaelhertig ,

Google Material design icons are quite different from other icon font libraries. Google is using native icon fonts. I have found a work around for that and updated the repo.

Please use v2.2.1 ,
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pretty-checkbox/2.2.0/pretty.min.css"/>
```

The mark up will be 

```html
<div class="pretty">
    <input type="checkbox" name="isSSL" />
    <label for="isSSL"><i class="g-mdi" data-icon="done"></i> Done</label>
</div>
```
The class name will be `g-mdi` and the icon name will be in the attribute `data-icon`

Thanks!

**Comment by lokesh-coder** [comment]
Hi @michaelhertig ,

Thanks for pointing out the issue. 

I found that the Google Material design icons are quite different from other icon font libraries. Google is using native ligature icon fonts. I have found a work around for that and updated the repo.

Please use v2.2.1 ,
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pretty-checkbox/2.2.1/pretty.min.css"/>
```

The mark up will be 

```html
<div class="pretty">
    <input type="checkbox" name="isSSL" />
    <label for="isSSL"><i class="g-mdi" data-icon="done"></i> Done</label>
</div>
```
The class name will be `g-mdi` and the icon name will be in the attribute `data-icon`

Demo:
https://lokesh-coder.github.io/pretty-checkbox/#custom-font-gmdi
https://jsbin.com/kequdev/edit?html,css,output

Thanks!

**Comment by michaelhertig** [comment]
Hi @lokesh-coder 

Wow, you were pretty fast. 👍 

I've also noticed that it is important to put the label **after** the input, otherwise it won't work. I recommend pointing that out in the docs.

Thanks a lot!

**Comment by lokesh-coder** [comment]
Thanks @michaelhertig 
I will definitely update the documentation.
I am closing the issue. But if you face any challenges feel free to open this again!
