### ISSUE TITLE
Any reason for margin?

### ISSUE THREAD

**Issue by denizdogan** [lokesh-coder/pretty-checkbox#7]
Thanks for this awesome library, exactly what I was looking for!

I was wondering, is there any reason why `.pretty` has `margin` set?

**Comment by lokesh-coder** [comment]
Hi @denizdogan , Thank you so much!

The only reason for right margin is to separate two checkbox/radio buttons when placed together. 
Bottom margin is just to give a uniform height for any font icons.

**Comment by denizdogan** [comment]
@lokesh-coder Okay, cool, it just caught me by surprise :) Thanks again
