### ISSUE TITLE
Toggle between three options

### ISSUE THREAD

**Issue by dowanx** [lokesh-coder/pretty-checkbox#9]
Is there a way to toggle through three options? 

Here is my HTML

```
<div class="pretty plain toggle">
                  <input type="checkbox"/> 
                  <label><i class="mdi mdi-thumb-up success"></i> PM</label>
                  <label><i class="mdi mdi-thumb-up success"></i> Planned WO</label>
                  <label><i class="mdi mdi-thumb-down danger"></i> Unplanned WO</label>
</div>
```

**Comment by lokesh-coder** [comment]
I am sorry @dowanx , I dont think that is possible without JS. :(

**Comment by lokesh-coder** [comment]
Closing now, But feel free to open if you got any questions.

And, I have updated the repo to [version 3](https://github.com/lokesh-coder/pretty-checkbox/blob/master/README.md) which has a feature to add third icon for `indeterminate` state. It might give you an idea. Here's the [documentation](https://lokesh-coder.github.io/pretty-checkbox/#states)

Thanks!
