### ISSUE TITLE
Start with state on by default

### ISSUE THREAD

**Issue by ghost** [lokesh-coder/pretty-checkbox#95]
How do you set the default state on?
As some radio/checkboxes start life active and some not active.

Also, is there a way to set the state of a collection of radio/checkboxes when a master item is clicked on/off?

**Comment by lokesh-coder** [comment]
hi @dxm38 I am not sure whether I got you question correctly. If you are referring to default checked state, you can add `checked` attribute to input element. Usually this is done using javascript dynamically. For a toggle, it would look like this,

```html
<div class="pretty p-icon p-toggle">
    <input type="checkbox"  checked/>  <!-- HERE -->
    <div class="state p-on">
        <i class="icon mdi mdi-microphone"></i>
        <label>ON</label>
    </div>
    <div class="state p-off">
        <i class="icon mdi mdi-microphone-off"></i>
        <label>OFF</label>
    </div>
</div>
```

**Comment by ghost** [comment]
D'Oh really sorry!!! I had a typo and stupidly assumed something else was going on. Really appreciate you getting back so quickly.
Oh and the project is beautiful. Thanks again!

**Comment by lokesh-coder** [comment]
Thanks @dxm38 ! :)
